Mh user languages (front end)
alexandria-reader/frontend pull request #102
Opened 2022-01-03 18:32 UTC by mrchrmn

## Description

Lots and lots of changes. In a nutshell:
* There is one `atom` state, `userState` that holds a user object of type `LoggedInUser`. This object also holds the current language selection.
* There is one derived `selector` state that allows for quicker access to the language ids in the user state object. 
* When the `App` component gets loaded, it checks for a token in `localStorage`. If there is a token, it gets send to the backend in return for the corresponding user data, which is then put into the user state. 
* Checking for the existence of a user state has replaced checking for the existence of the token. Exception: `index.tsx` cannot use state because there are no proper React components to access state from. 

## Type of Changes

|     | Type                       |
| --- | -------------------------- |
| :heavy_check_mark:     | :sparkles: New feature     |
|  :heavy_check_mark:    | :hammer: Refactoring       |

## Testing Steps / QA Criteria

**Test thoroughly, please, as there are many crucial changes.**

2022-01-03 21:16 UTC, danachen commented
Sign-in, texts and words all seem to work as before. Sign up is having issues however, get `Could not find language with this id.` when signing up for new account.

2022-01-04 08:47 UTC, eamon0989 requested changes
Tests are not working as token is not provided.

2022-01-04 11:41 UTC, mrchrmn commented
Reworked the user state which doesn't hold language objects anymore.
Sign up, log in, returning to a session, getting current user language settings on different device all work now.
I x'ed out the tests for now.

2022-01-04 13:55 UTC, eamon0989 approved these changes

2022-01-04 13:56 UTC, merged